{{- if .Values.pihole.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pihole.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
stringData:
  {{ .Values.pihole.secret.key }}: {{ .Values.pihole.secret.password }}
{{- end }}
